name: "Get CI"

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - '*'

jobs:
  macos-run-tests:
    name: Unit Tests (Xcode ${{ matrix.xcode }})
    strategy:
      fail-fast: false
      matrix:
        xcode: ["13.4.1", "13.3.1", "13.2.1"]
        include:
          - xcode: "13.4.1"
            macos: macOS-12
          - xcode: "13.3.1"
            macos: macOS-12
          - xcode: "13.2.1"
            macos: macOS-11
    runs-on: ${{ matrix.macos }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: swift test

  linux-run-tests:
    name: Unit Tests (Linux, Swift ${{ matrix.swift }})
    strategy:
      fail-fast: false
      matrix:
        swift: ["5.5", "5.6"]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: swift test

  discover-typos:
    name: Discover Typos
    runs-on: macOS-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Discover typos
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install codespell
          codespell --ignore-words-list="inout,theis" --skip="./.build/*,./Tests/GetTests/Mocker/*"
